### ISSUE TITLE
Test Automation: Customer deletion removes all data for associated users and providers

### ISSUE THREAD

**Issue by LandoCalrizzian** [project-koku/hansei#5]
Verify that deleting a customer removes all associated data for users and providers

Dev cards:
- https://github.com/project-koku/koku/issues/118
- https://github.com/project-koku/koku/issues/167
- https://github.com/project-koku/koku/issues/191
- https://github.com/project-koku/koku/issues/173

**Comment by nachandr** [comment]
This was closed by https://app.zenhub.com/workspace/o/project-koku/hansei/issues/24
